{% set name = "pplpy" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8289c50d680ce3f9eacac666cb4cdbbd8a711959e7cc7cf06f7fdb4035d0cc5d

build:
  number: 0
  skip: true  # [win or py<312]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-build-isolation --config-settings=setup-args=--default-library=shared --config-settings=setup-args=--wrap-mode=nofallback

requirements:
  build:
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython
    - cysignals
    - gmpy2
    - pkg-config
    - meson
    - ninja
    - jinja2
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - ppl
    - python
    - cysignals
    - cython
    - pip
    - meson-python
    - gmp
    - mpfr
    - mpc
    - gmpy2
  run:
    - python
    - cysignals
    - gmp
    - mpfr
    - mpc
    - gmpy2
    - {{ pin_compatible("ppl", max_pin="x.x") }}

test:
  imports:
    - ppl

about:
  home: https://www.sagemath.org/pplpy/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: This Python package provides a wrapper to the C++ Parma Polyhedra Library (PPL).
  dev_url: https://github.com/sagemath/pplpy

extra:
  recipe-maintainers:
    - isuruf
    - videlec
