{% set name = "pplpy" %}
{% set version = "0.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eaa50927321fb6c5eb8283262c38f4e9ace26263baf06651deebc271031ef031

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - cysignals                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ppl
    - python
    - cysignals
    - cython
    - pip
    - gmp
    - mpfr
    - mpc
    - gmpy2
  run:
    - python
    - cysignals
    - gmp
    - mpfr
    - mpc
    - gmpy2
    - {{ pin_compatible("ppl", max_pin="x.x") }}

test:
  imports:
    - ppl

about:
  home: https://www.sagemath.org/pplpy/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: This Python package provides a wrapper to the C++ Parma Polyhedra Library (PPL).
  dev_url: https://github.com/sagemath/pplpy

extra:
  recipe-maintainers:
    - isuruf
